version: '3.3'

services:
  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka"
    ports:
      - "9092:9092"
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_HOST_NAME: "${KAFKA_HOST:-localhost}"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "campaign-booking:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
